### ISSUE TITLE
从数据库获取分类

### ISSUE THREAD

**Issue by Nomango** [Colocust/CoolCoder#2]
目前“我要提问”和“发布文章”处的分类是hardcode静态文本，需要将它改为动态获取

- [x] 在“全部问答”界面增加提问框  https://github.com/Colocust/CoolCoder/commit/f7b4bdc84d19b00495ba1133c38265a6d24565d9

- [x] 删除“我要提问”按钮的弹窗功能，使它链接到“全部问答”界面 https://github.com/Colocust/CoolCoder/commit/f7b4bdc84d19b00495ba1133c38265a6d24565d9

- [x] 从数据库获取分类并动态显示 https://github.com/Colocust/CoolCoder/commit/f7b4bdc84d19b00495ba1133c38265a6d24565d9

- [x] 在数据库中增加分类项 https://github.com/Colocust/CoolCoder/commit/f7b4bdc84d19b00495ba1133c38265a6d24565d9

**Comment by Colocust** [comment]
已完成
