### ISSUE TITLE
UE编辑器问题

### ISSUE THREAD

**Issue by Nomango** [Colocust/CoolCoder#3]
“我要提问”、“发布文章”、“发布作品”、“发布活动”页面，以及各页面的评论输入框，它们的UE编辑器都有问题，可按以下步骤修复

- [x] 限制可输入的字数（300-500） https://github.com/Colocust/CoolCoder/commit/01ae09ad690d81cb97d16cee337ec4b8c1ec1d31
- [x] 屏幕分辨率较大时，“提问”处的弹窗不会随编辑器的大小伸缩 https://github.com/Colocust/CoolCoder/commit/01ae09ad690d81cb97d16cee337ec4b8c1ec1d31

修改时需注意：

- 尽量使用UE和Layui提供的接口完成功能
- Layui的弹窗应该提供了开启垂直滚动的功能

**Comment by Colocust** [comment]
已完成
